### ISSUE TITLE
无法上传歌曲

### ISSUE THREAD

**Issue by ABKQPO** [lgc-NB2Dev/nonebot-plugin-multincm#11]
```
10-25 22:48:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=417)
10-25 22:48:58 [ERROR] nonebot_plugin_multincm | Upload 歌曲 863515475 failed
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_multincm\__main__.py", line 448, in _
    await upload_music(song)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_multincm\__main__.py", line 160, in upload_music
    file_path = download_ret["file"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by XieXiLin2** [comment]
考虑到是网络问题，请检查网络环境并重新尝试上传。

**Comment by ABKQPO** [comment]
经过测试，无论是否有代理均会出现此问题

**Comment by XieXiLin2** [comment]
那么，您的插件版本 & Python 版本是？

**Comment by ABKQPO** [comment]
插件版本0.4.4，python版本3.10，使用账号有VIP

**Comment by XieXiLin2** [comment]
大概率是 Gocq 那边没有下载成功，先看看是不是歌曲没有解析到（最少都需要 Bot 发生一次歌曲卡片才算解析到了）。
如果解析到 upload 还是报错的话注意观察 Gocq 的日志，看看是不是自己的问题。
