### ISSUE TITLE
【bug】/发送语音没有任何响应

### ISSUE THREAD

**Issue by mcxiaochenn** [lgc-NB2Dev/nonebot-plugin-multincm#25]
.env.*文件中的配置文件部分
#NoneBot-Plugin-MultiNCM
NCM_PHONE=xxx
NCM_PASSWORD=xxx
NCM_ENABLE_RECORD=True

以下配图是测试截图
![Screenshot_2024-05-20-04-12-06-513_com microsoft rdc androidx-edit](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/8714beac-3ee1-4e55-a72c-d7285ec40938)
![Screenshot_2024-05-20-04-11-59-973_com microsoft rdc androidx](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/c218a070-d319-4f12-bfe7-94e8272e45b3)

**Comment by mcxiaochenn** [comment]
/tts可以正常发送语音，已排除协议不支持的问题
![Screenshot_2024-05-20-04-20-14-125_com tencent mobileqq](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/43b7be89-94db-4d60-a6db-abd6964d256a)

**Comment by XieXiLin2** [comment]
- `NCM_ENABLE_RECORD` 配置项是否为 `True`
- 指令是我的问题，写错了（ -> 是 `语音` / `record`

**Comment by mcxiaochenn** [comment]
还是不行
![Screenshot_2024-05-20-19-51-35-248_com microsoft rdc androidx-edit](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/cd4c0a22-2985-4c6b-9df1-40dfc9bd510d)
![Screenshot_2024-05-20-19-50-59-449_com tencent mobileqq](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/3ce5b8eb-a6f5-4957-b0a3-f53c8738f37d)
![Screenshot_2024-05-20-19-50-39-930_com microsoft rdc androidx](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/b670e5a1-6ca5-4975-91e5-e2bd7bc9e21d)
![Screenshot_2024-05-20-19-47-21-178_com microsoft rdc androidx](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/aa33080e-8fd0-4468-884f-167dc4d7d57d)

**Comment by mcxiaochenn** [comment]
我可没这么傻。。。。。。nb run --reload也不行，而且我第一次提交issue就已经加上去了，尝试更改了排序也还是不行
![Uploading Screenshot_2024-05-20-20-00-27-811_com.microsoft.emmx-edit.jpg…]()

**Comment by mcxiaochenn** [comment]
![Screenshot_2024-05-20-20-06-16-131_com microsoft rdc androidx](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/3ed6e590-f917-446c-93b5-548fe73e2f0c)
![Screenshot_2024-05-20-20-06-00-432_com microsoft rdc androidx](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/04afb1c2-f5ca-44d6-b109-91e29e05f8ba)
plugins = ["nonebot_plugin_picmcstat", "nonebot_plugin_multincm", "nonebot_plugin_epicfree", "nonebot_plugin_memes", "nonebot_plugin_bilibilibot", "nonebot_plugin_apscheduler", "nonebot_plugin_friends", "nonebot_plugin_fishing", "nonebot_plugin_date_name", "nonebot_plugin_justsix", "nonebot_plugin_admin"]

python 3.11
系统winserver2016刚装的系统，已安装ffemg（好像是叫这个名，且正确配置环境变量），已安装最新vc运行库

已重启电脑排除windows bug
已重装python、pipx等环境排除环境问题

**Comment by XieXiLin2** [comment]
等明天晚上测试一下再确认。现在也不好说（
执行 `nb self list` 发一下截图。

**Comment by mcxiaochenn** [comment]
好的（
![Screenshot_2024-05-20-20-26-40-020_com microsoft rdc androidx-edit](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/130777336/52d3f806-edb7-4513-ba9d-bd38bc5e2e53)

**Comment by mcxiaochenn** [comment]
上头说了/tts可以正常输出语音，不存在ffmpeg的问题和协议端的问题，插件从阿里云镜像下的，确实有可能，我现在更新试试

**Comment by mcxiaochenn** [comment]
尝试卸载后从pypi源重新下载，依旧不行:(

**Comment by lgc2333** [comment]
安装dev版本
`pip install nonebot-plugin-multincm==0.5.0.dev10`

**Comment by mcxiaochenn** [comment]
我稍后测试，dev版本有什么新特性吗
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年05月23日 12:35 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [lgc-NB2Dev/nonebot-plugin-multincm] 【bug】/发送语音没有任何响应 (Issue #25) 
安装dev版本
pip install nonebot-plugin-multincm==0.5.0.dev10

**Comment by lgc2333** [comment]
正式版本已经很久没更新了

**Comment by mcxiaochenn** [comment]
05-23 12:43:29 [INFO] nonebot_plugin_memes | 正在检查资源文件... 
Task exception was never retrieved 
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()> 
Traceback (most recent call last): 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 272, in run 
await self._transport.connect() 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 133, in connect 
raise exc 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect 
self._proc = await asyncio.create_subprocess_exec( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec 
transport, protocol = await loop.subprocess_exec( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec 
transport = await self._make_subprocess_transport( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport 
raise NotImplementedError 
NotImplementedError 
05-23 12:43:34 [ERROR] uvicorn | Traceback (most recent call last): 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\starlette\routing.py", line 732, in lifespan 
async with self.lifespan_context(app) as maybe_state: 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__ 
return await anext(self.gen) 
^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager 
await self._lifespan.startup() 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup 
await self._run_lifespan_func(self._startup_funcs) 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func 
await cast(ASYNC_LIFESPAN_FUNC, func)() 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init 
browser = await get_browser(**kwargs) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser 
return _browser if _browser and _browser.is_connected() else await init(**kwargs) 
^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init 
_playwright = await async_playwright().start() 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start 
return await self.__aenter__() 
^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__ 
playwright = AsyncPlaywright(next(iter(done)).result()) 
^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect 
self._proc = await asyncio.create_subprocess_exec( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec 
transport, protocol = await loop.subprocess_exec( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec 
transport = await self._make_subprocess_transport( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport 
raise NotImplementedError 
NotImplementedError 
05-23 12:43:34 [ERROR] uvicorn | Application startup failed. Exiting. 
pip install nonebot-plugin-multincm==0.5.0.dev10 -U后报错，禁用ncm插件后正常启动
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年05月23日 12:35 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [lgc-NB2Dev/nonebot-plugin-multincm] 【bug】/发送语音没有任何响应 (Issue #25) 
安装dev版本
pip install nonebot-plugin-multincm==0.5.0.dev10

**Comment by lgc2333** [comment]
https://nonebot.dev/docs/advanced/driver#fastapi%E9%BB%98%E8%AE%A4

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/59048777/54be5cc3-2ffc-4a02-92a6-92eb20c82ab6)

**Comment by XieXiLin2** [comment]
该 Issue 超过一周未回复，将关闭。
