### ISSUE TITLE
为什么装上之后无法启动bot

### ISSUE THREAD

**Issue by BruceArc** [lgc-NB2Dev/nonebot-plugin-multincm#28]
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
06-20 17:14:04 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

06-20 17:14:04 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by BruceArc** [comment]
好快的回复，已解决，非常感谢

**Comment by nansou520** [comment]
怎么解决的

**Comment by XieXiLin2** [comment]
> 怎么解决的
> 

上面不已经发了吗……

**Comment by nansou520** [comment]
把fastapi_reload改成True么,我试过了,nb run --reload我也试过了,都没有用

**Comment by XieXiLin2** [comment]
> 把fastapi_reload改成True么,我试过了,nb run --reload我也试过了,都没有用

？让你改成 `False`

还是不行请附上报错内容

**Comment by nansou520** [comment]
改成False也没有用
报错内容跟一楼一模一样:
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Connection.run() done, defined at C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    raise exc
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
07-05 19:11:24 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init
    _playwright = await async_playwright().start()
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

07-05 19:11:24 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by XieXiLin2** [comment]
> 改成False也没有用
> 报错内容跟一楼一模一样:
> Task exception was never retrieved
> future: <Task finished name='Task-23' coro=<Connection.run() done, defined at C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
> Traceback (most recent call last):
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
>     await self._transport.connect()
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
>     raise exc
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
>     self._proc = await asyncio.create_subprocess_exec(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
>     transport, protocol = await loop.subprocess_exec(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
>     transport = await self._make_subprocess_transport(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
>     raise NotImplementedError
> NotImplementedError
> 07-05 19:11:24 [ERROR] uvicorn | Traceback (most recent call last):
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 734, in lifespan
>     async with self.lifespan_context(app) as maybe_state:
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
>     return await anext(self.gen)
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
>     await self._lifespan.startup()
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
>     await self._run_lifespan_func(self._startup_funcs)
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
>     await cast(ASYNC_LIFESPAN_FUNC, func)()
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init
>     browser = await get_browser(**kwargs)
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser
>     return _browser if _browser and _browser.is_connected() else await init(**kwargs)
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init
>     _playwright = await async_playwright().start()
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
>     return await self.__aenter__()
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
>     playwright = AsyncPlaywright(next(iter(done)).result())
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
>     self._proc = await asyncio.create_subprocess_exec(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
>     transport, protocol = await loop.subprocess_exec(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
>     transport = await self._make_subprocess_transport(
>   File "C:\Users\nanso\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
>     raise NotImplementedError
> NotImplementedError
> 
> 07-05 19:11:24 [ERROR] uvicorn | Application startup failed. Exiting.

那仍然是你的问题，好好检查一下是不是没改对

like 你改错 env 文件了, etc.
