### ISSUE TITLE
none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by Sevenyine** [lgc-NB2Dev/nonebot-plugin-multincm#6]
插件版本：0.3.9
启动无报错，在指令点歌/发送网易云音乐卡片时出现如下报错：
QQ内报错：`获取歌曲播放链接失败，请检查后台输出`
后台报错：
```
08-27 19:31:54 [ERROR] nonebot_plugin_multincm | 获取歌曲播放链接失败
Traceback (most recent call last):
  File "/root/GZbot2/bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_multincm/__main__.py", line 448, in _
    await send_music(song)
> File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_multincm/__main__.py", line 197, in send_music
    audio_info = await get_track_audio([song_id], bitrate)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_multincm/data_source.py", line 85, in get_track_audio
    return [TrackAudio(**x) for x in cast(List[dict], res["data"])]
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_multincm/data_source.py", line 85, in <listcomp>
    return [TrackAudio(**x) for x in cast(List[dict], res["data"])]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for TrackAudio
url
  none is not an allowed value (type=type_error.none.not_allowed)
md5
  none is not an allowed value (type=type_error.none.not_allowed)
```

.env文件
```
NCM_PHONE = "手机"
NCM_PASSWORD = "密码"
NCM_LIST_LIMIT = 20
NCM_LIST_FONT = "LXGW WenKai GB Screen"
NCM_AUTO_RESOLVE = True
NCM_ILLEGAL_CMD_FINISH = True
NCM_USE_PLAYWRIGHT = True
NCM_DELETE_LIST_MSG_DELAY = [10.5, 20.0]
其他均无配置
```

**Comment by lgc2333** [comment]
网易云账号有没有会员，没会员为正常情况

**Comment by lgc2333** [comment]
黑胶账号没问题
氪金吧，少年
![Screenshot_20230829-010942](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/59048777/06e9dacf-09c6-45de-9370-665326553511)

**Comment by Sevenyine** [comment]
> 黑胶账号没问题
> 氪金吧，少年

嘶我好像在删除data/multincm的session之后又可以正常点歌了，可能是登录状态过期了，虽然我也没改过密码
或许这个登录状态应该每次启动nb刷新？（）不过问题解决啦

**Comment by lgc2333** [comment]
会检查登录态来着
![Screenshot_20230829-105056](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/59048777/0e152412-2192-473b-90a8-21ce9b941086)

**Comment by Sevenyine** [comment]
> 会检查登录态来着
> 
> https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/blob/d51b10371db65e051ff89d801eaeec28eeedb9a0/nonebot_plugin_multincm/data_source.py#L159-L172

确实会，我记得当时我看到了他说欢迎+我的账号昵称但是点歌还是有问题
甚至我直接删掉让他匿名态登陆他都可以点歌（）很神奇 而且我的账号也没被封禁之类的，手机上能上去
不过现在解决了就是了，谢谢！(*≧ω≦)
